### ISSUE TITLE
Won't work with Oppo HEIC Photos

### ISSUE THREAD

**Issue by thatrossachap** [catdad-experiments/heic-app#7]
This project looks really great, and I was excited for it helping out with my Oppo Find X3 Pro, but alas, I get an error message that says the photo isn't a HEIC file... when it is.

**Comment by catdad** [comment]
Do you have an example photo you can provide that causes this error?

**Comment by thatrossachap** [comment]
I do, but you can't add HEIC files to Github or Imgur, but this is a screenshot of the photo and the error message, if that is at all helpful.
![image](https://user-images.githubusercontent.com/67339176/127662132-99878199-44ce-4df4-991f-aeea7f529b9a.png)
![image](https://user-images.githubusercontent.com/67339176/127662140-575301bd-73ff-454b-bf68-f1b2c16838c9.png)

**Comment by catdad** [comment]
It is not that I don't believe you when you say there is an error. I am sure you have no reason to lie to me. But unless I can reproduce it, I cannot fix it.

**Comment by thatrossachap** [comment]
I just don't know how I can get the photo to you because Gmail and Google Drive automatically converts the photo to JPEG when I send them through
